### ISSUE TITLE
无法使用过滤器

### ISSUE THREAD

**Issue by ddgweb** [gabrielxvx/zh-fiddler#6]
![33.jpg](https://i.loli.net/2020/04/30/O3lukZTdDMtJyK5.jpg)
![34.jpg](https://i.loli.net/2020/04/30/nuUkc4RJzir5Twh.jpg)

**Comment by ddgweb** [comment]
![35.jpg](https://i.loli.net/2020/04/30/UekvEDRLTiNK7st.jpg)

**Comment by gabrielxvx** [comment]
剩余插件已汉化同步了,可以重新下载试试看.

**Comment by ddgweb** [comment]
> 剩余插件已汉化同步了,可以重新下载试试看.

用心了，谢谢！
